/**
 * Enumeración de las lenguas del Perú.
 */
const TIPOS_LENGUAS = Object.freeze({
    ACHUAR:                   'Achuar',
    AIMARA:                   'Aimara',
    AMAHUACA:                 'Amahuaca',
    ARABELA:                  'Arabela',
    ASHANINKA:                'Ashaninka',
    ASHENINKA:                'Asheninka',
    AWAJUN:                   'Awajún',
    BORA:                     'Bora',
    CASHINAHUA:               'Cashinahua',
    CHAMIKURO:                'Chamikuro',
    ESE_EJA:                  'Ese Eja',
    HARAKBUT:                 'Harakbut',
    IKITU:                    'Ikitu',
    INAPAR:                   'Iñapar',
    ISKONAWA:                 'Iskonawa',
    JAQARU:                   'Jaqaru',
    KAKATAIBO:                'Kakataibo',
    KAKINTE:                  'Kakinte',
    KANDOZI_CHAPRA:           'Kandozi-Chapra',
    KAPANAWA:                 'Kapanawa',
    KAWKI:                    'Kawki',
    KUKAMA_KUKAMIRIA:         'Kukama Kukamiria',
    MADIJA:                   'Madija',
    MAIJI_KI:                 'Maijɨki',
    MATSÉS:                   'Matsés',
    MATSIGENKA:               'Matsigenka',
    MATSIGENKA_MONTETOKUNIRIRA: 'Matsigenka Montetokunirira',
    MUNICHÍ:                  'Munichi',
    MURUI_MUINANɨ:            'Murui-Muinanɨ',
    NAHUA:                    'Nahua',
    NOMATSIGENGA:             'Nomatsigenga',
    OCAINA:                   'Ocaina',
    OMAGUA:                   'Omagua',
    QUECHUA:                  'Quechua',
    RESÍGARO:                 'Resígaro',
    SECOYA:                   'Secoya',
    SHARANAHUA:               'Sharanahua',
    SHAWI:                    'Shawi',
    SHIPIBO_KONIBO:           'Shipibo-Konibo',
    SHIWILU:                  'Shiwilu',
    TAUSHIRO:                 'Taushiro',
    TICUNA:                   'Ticuna',
    URARINA:                  'Urarina',
    WAMPIS:                   'Wampis',
    YAGUA:                    'Yagua',
    YAMINA_HUA:               'Yaminahua',
    YANESHA:                  'Yanesha',
    YINE:                     'Yine',
    LENGUA_DE_SENAS:          'Lengua de señas',
    ESPANOL:                  'Español',
    INGLES:                   'Inglés',
    OTRO:                     'Otro'
});

export default TIPOS_LENGUAS;